// Central registry of all UserDefaults keys used in KeyLens.
// Use these constants everywhere instead of raw strings.
enum UDKeys {
    static let advancedMode                = "advancedMode"
    static let appAppearance               = "appAppearance"
    static let appLanguage                 = "appLanguage"
    static let bigramDrillIKIThreshold     = "bigramDrillIKIThreshold"
    static let bigramHeatmapTopN           = "bigramHeatmapTopN"
    static let chartTheme                  = "chartTheme"
    static let drillPresets                = "drillPresets"
    static let frequentChartsSortDescending = "frequentChartsSortDescending"
    static let heatmapLastResolvedTemplate = "heatmapLastResolvedTemplate"
    static let heatmapTemplate             = "heatmapTemplate"
    static let kleCustomKeywords           = "kleCustomKeywords"
    static let kleCustomLayoutFileName     = "kleCustomLayoutFileName"
    static let kleCustomLayoutJSON         = "kleCustomLayoutJSON"
    static let kleCustomLayoutURL          = "kleCustomLayoutURL"
    static let kleProfiles                 = "kleProfiles"
    static let kleSelectedProfileID        = "kleSelectedProfileID"
    static let milestoneInterval           = "milestoneInterval"
    static let perfProfilingEnabled        = "perfProfilingEnabled"
    static let selectedChartTab            = "selectedChartTab"
    static let selectedActivitySubTab      = "selectedActivitySubTab"
    static let selectedMouseSubTab         = "selectedMouseSubTab"
    static let speedometerSize             = "speedometerSize"
    static let thumbOptimizationEnabled    = "thumbOptimizationEnabled"
    static let trainingSessionLength       = "trainingSessionLength"
    static let wpmGaugeOverlayX            = "wpmGaugeOverlayX"
    static let wpmGaugeOverlayY            = "wpmGaugeOverlayY"
}
