import SwiftUI

// MARK: - WeeklySummaryCardView

/// A self-contained card view that summarises one week of typing activity.
/// Rendered off-screen via ImageRenderer and saved as PNG.
struct WeeklySummaryCardView: View {
    let data: WeeklySummaryData

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            headerSection
            Divider().padding(.vertical, 12)
            statsRow
            Divider().padding(.vertical, 12)
            topKeysSection
            Divider().padding(.vertical, 12)
            footerRow
        }
        .padding(24)
        .frame(width: 480)
        .background(Color(NSColor.windowBackgroundColor))
        .clipShape(RoundedRectangle(cornerRadius: 16))
        .overlay(
            RoundedRectangle(cornerRadius: 16)
                .stroke(Color.primary.opacity(0.1), lineWidth: 1)
        )
    }

    // MARK: - Header

    private var headerSection: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Image(systemName: "keyboard")
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundColor(.accentColor)
                Text(L10n.shared.weeklySummaryCardTitle)
                    .font(.system(size: 18, weight: .semibold))
                Spacer()
            }
            Text(data.weekRange)
                .font(.system(size: 13))
                .foregroundColor(.secondary)
        }
    }

    // MARK: - Stats row

    private var statsRow: some View {
        HStack(spacing: 0) {
            statCell(
                icon: "character.cursor.ibeam",
                label: L10n.shared.weeklySummaryCardTotalKeys,
                value: data.totalKeystrokes.formatted()
            )
            Divider().frame(height: 48)
            statCell(
                icon: "speedometer",
                label: L10n.shared.weeklySummaryCardWPM,
                value: data.estimatedWPM.map { String(format: "%.0f", $0) } ?? "—"
            )
            Divider().frame(height: 48)
            statCell(
                icon: "flame",
                label: L10n.shared.weeklySummaryCardStreak,
                value: "\(data.streak)"
            )
            Divider().frame(height: 48)
            statCell(
                icon: "heart.fill",
                label: L10n.shared.weeklySummaryCardErgonomicScore,
                value: String(format: "%.0f", data.ergonomicScore)
            )
        }
    }

    private func statCell(icon: String, label: String, value: String) -> some View {
        VStack(spacing: 4) {
            Image(systemName: icon)
                .font(.system(size: 14))
                .foregroundColor(.accentColor)
            Text(value)
                .font(.system(size: 20, weight: .bold, design: .rounded))
            Text(label)
                .font(.system(size: 10))
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
    }

    // MARK: - Top keys

    private var topKeysSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(L10n.shared.weeklySummaryCardTopKeys)
                .font(.system(size: 12, weight: .semibold))
                .foregroundColor(.secondary)
            HStack(spacing: 8) {
                ForEach(data.topKeys, id: \.key) { entry in
                    VStack(spacing: 2) {
                        Text(entry.key)
                            .font(.system(size: 15, weight: .bold, design: .monospaced))
                            .frame(width: 36, height: 36)
                            .background(Color.accentColor.opacity(0.12))
                            .clipShape(RoundedRectangle(cornerRadius: 6))
                        Text(entry.count.formatted())
                            .font(.system(size: 10))
                            .foregroundColor(.secondary)
                    }
                }
            }
        }
    }

    // MARK: - Footer

    private var footerRow: some View {
        HStack {
            Spacer()
            Text("Generated by KeyLens")
                .font(.system(size: 10))
                .foregroundColor(.secondary.opacity(0.5))
        }
    }
}

// MARK: - WeeklySummaryData

struct WeeklySummaryData {
    let weekRange: String
    let totalKeystrokes: Int
    let estimatedWPM: Double?
    let streak: Int
    let ergonomicScore: Double
    let topKeys: [(key: String, count: Int)]

    /// Build from current KeyCountStore state, using the last 7 days as the week window.
    static func current() -> WeeklySummaryData {
        let store = KeyCountStore.shared
        let cal = Calendar.current

        // Week range label
        let today = Date()
        let monday = cal.date(from: cal.dateComponents(
            [.yearForWeekOfYear, .weekOfYear], from: today)) ?? today
        let sunday = cal.date(byAdding: .day, value: 6, to: monday) ?? today

        let fmt = DateFormatter()
        fmt.dateFormat = "MMM d"
        let weekRange = "\(fmt.string(from: monday)) – \(fmt.string(from: sunday))"

        // Total keystrokes for the last 7 days
        let dailies = store.dailyTotals(last: 7)
        let weekTotal = dailies.reduce(0) { $0 + $1.count }

        return WeeklySummaryData(
            weekRange: weekRange,
            totalKeystrokes: weekTotal,
            estimatedWPM: store.estimatedWPM,
            streak: store.currentStreak(),
            ergonomicScore: store.currentErgonomicScore,
            topKeys: store.topKeys(limit: 5)
        )
    }
}

// MARK: - WeeklySummaryGenerator

enum WeeklySummaryGenerator {

    private static let reportsDir: URL = {
        FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("KeyLens/reports")
    }()

    private static let lastGenerationKey = "weeklySummaryLastGeneratedDate"

    /// Returns true if today is Monday and a card hasn't been generated yet this week.
    static var shouldAutoGenerate: Bool {
        let cal = Calendar.current
        guard cal.component(.weekday, from: Date()) == 7 else { return false } // 7 = Saturday
        let today = Date()
        let lastDate = UserDefaults.standard.object(forKey: lastGenerationKey) as? Date
        if let last = lastDate, cal.isDate(last, inSameDayAs: today) { return false }
        return true
    }

    /// Renders the card and saves it to the reports directory. Returns the saved URL or nil on failure.
    @MainActor
    @discardableResult
    static func generate(to url: URL? = nil) -> URL? {
        let data = WeeklySummaryData.current()
        let view = WeeklySummaryCardView(data: data)

        let renderer = ImageRenderer(content: view)
        renderer.scale = 2.0  // retina quality

        guard let cgImage = renderer.cgImage else { return nil }

        let destURL: URL
        if let provided = url {
            destURL = provided
        } else {
            let fmt = DateFormatter()
            fmt.dateFormat = "yyyy-MM-dd"
            let tag = fmt.string(from: Date())
            try? FileManager.default.createDirectory(at: reportsDir, withIntermediateDirectories: true)
            destURL = reportsDir.appendingPathComponent("KeyLens_weekly_\(tag).png")
        }

        let bitmapRep = NSBitmapImageRep(cgImage: cgImage)
        guard let pngData = bitmapRep.representation(using: .png, properties: [:]) else { return nil }

        do {
            try pngData.write(to: destURL)
            UserDefaults.standard.set(Date(), forKey: lastGenerationKey)
            return destURL
        } catch {
            return nil
        }
    }
}
